/*
 * This file is generated by jOOQ.
 */

package edu.java.repository.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private String type;
    private OffsetDateTime updatedAt;
    private OffsetDateTime lastCheckedAt;

    public Link() {
    }

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.type = value.type;
        this.updatedAt = value.updatedAt;
        this.lastCheckedAt = value.lastCheckedAt;
    }

    @ConstructorProperties({"id", "url", "type", "updatedAt", "lastCheckedAt"})
    public Link(
        @Nullable Long id,
        @NotNull String url,
        @NotNull String type,
        @Nullable OffsetDateTime updatedAt,
        @Nullable OffsetDateTime lastCheckedAt
    ) {
        this.id = id;
        this.url = url;
        this.type = type;
        this.updatedAt = updatedAt;
        this.lastCheckedAt = lastCheckedAt;
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>public.link.type</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.link.type</code>.
     */
    public void setType(@NotNull String type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.link.last_checked_at</code>.
     */
    @Nullable
    public OffsetDateTime getLastCheckedAt() {
        return this.lastCheckedAt;
    }

    /**
     * Setter for <code>public.link.last_checked_at</code>.
     */
    public void setLastCheckedAt(@Nullable OffsetDateTime lastCheckedAt) {
        this.lastCheckedAt = lastCheckedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.url == null) {
            if (other.url != null) {
                return false;
            }
        } else if (!this.url.equals(other.url)) {
            return false;
        }
        if (this.type == null) {
            if (other.type != null) {
                return false;
            }
        } else if (!this.type.equals(other.type)) {
            return false;
        }
        if (this.updatedAt == null) {
            if (other.updatedAt != null) {
                return false;
            }
        } else if (!this.updatedAt.equals(other.updatedAt)) {
            return false;
        }
        if (this.lastCheckedAt == null) {
            if (other.lastCheckedAt != null) {
                return false;
            }
        } else if (!this.lastCheckedAt.equals(other.lastCheckedAt)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.lastCheckedAt == null) ? 0 : this.lastCheckedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(type);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(lastCheckedAt);

        sb.append(")");
        return sb.toString();
    }
}
